language: erlang
otp_release:
  - 18.2.1
  - 18.1
  - 18.0
  - 17.5
  - R16B03

node_js:
  - 6

cache:
  directories:
    - node_modules

script:
  - npm run flow
  - CI=true npm run test
  - make test
